allowBuilds:
  esbuild: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plus: 0.2.6

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

storeDir: C:\Users\czer3\AppData\Local\pnpm\store\v10
